project:
  name: "Themes Changing VS Code Extension"
  type: "vscode-extension"
  description: "A VS Code extension for automatic theme switching with BMad integration"
  version: "0.1.0"
  
bmad:
  version: "1.0.0"
  agent: "bmad-master"
  
settings:
  default_output_format: "markdown"
  auto_save: true
  backup_enabled: true
  
paths:
  source: "./src"
  output: "./out"
  docs: "./docs"
  templates: "./.bmad-core/templates"
  tasks: "./.bmad-core/tasks"
  checklists: "./.bmad-core/checklists"
  data: "./.bmad-core/data"
  workflows: "./.bmad-core/workflows"
  
project_context:
  domain: "Developer Tools"
  technology_stack:
    - "TypeScript"
    - "VS Code Extension API"
    - "Node.js"
  
  current_features:
    - "Automatic theme switching"
    - "Time-based theme changes"
    - "Interval-based theme changes"
    - "Theme configuration UI"
    - "Pause/Resume functionality"
  
  target_users:
    - "VS Code developers"
    - "Theme enthusiasts"
    - "Productivity-focused users"
  
integration:
  vscode:
    commands_prefix: "themes-changing"
    settings_prefix: "themesChanging"
    webview_enabled: true
  
  bmad:
    commands_enabled: true
    task_execution: true
    template_system: true
    checklist_support: true
